In [1]:
import pandas as pd
import numpy as np

In [2]:
credit = pd.read_csv('/Users/mac/Documents/ML_Prac/Recommender/tmdb_5000_credits.csv')

In [3]:
movies = pd.read_csv('/Users/mac/Documents/ML_Prac/Recommender/tmdb_5000_movies.csv')

In [4]:
credit.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1340,37000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",http://werethemillers.warnerbros.com,138832,"[{""id"": 534, ""name"": ""mexico""}, {""id"": 6149, ""...",en,We're the Millers,A veteran pot dealer creates a fake family as ...,100.348805,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-08-07,269994119,110.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,-If anyone asks.,We're the Millers,6.8,2972
1887,30000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,8976,"[{""id"": 242, ""name"": ""new york""}, {""id"": 367, ...",en,A Lot Like Love,"On a flight from Los Angeles to New York, Oliv...",19.212552,"[{""name"": ""Mile High Productions"", ""id"": 2976}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-04-22,42886719,107.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There's nothing better than a great romance......,A Lot Like Love,6.5,318
631,59000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 35, ""...",http://www.iceagemovies.com/films/ice-age,425,"[{""id"": 311, ""name"": ""human evolution""}, {""id""...",en,Ice Age,"With the impending ice age almost upon them, a...",99.561972,"[{""name"": ""Twentieth Century Fox Film Corporat...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2002-03-10,383257136,81.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They came. They thawed. They conquered.,Ice Age,7.1,3857
2762,13000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 80, ""nam...",NaN,11592,"[{""id"": 3451, ""name"": ""housewife""}, {""id"": 455...",en,Serial Mom,A picture perfect middle class family is shock...,6.170139,"[{""name"": ""Savoy Pictures"", ""id"": 11308}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-04-13,7820688,95.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Every Mom Wants to Be Wanted, But Not For Murd...",Serial Mom,6.4,135
3450,6000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",NaN,1725,"[{""id"": 100, ""name"": ""slum""}, {""id"": 542, ""nam...",en,West Side Story,In the slums of the upper West Side of Manhatt...,23.431117,"[{""name"": ""United Artists"", ""id"": 60}, {""name""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1961-10-18,43656822,152.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The screen achieves one of the great entertain...,West Side Story,7.0,389

In [6]:
credit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [8]:
# Picking those columns will be necessary in Recommending Movies (in Movies Dataset)

In [9]:
# genres , keywords , overview , title

In [10]:
movies = movies[['title','genres','keywords','overview']]

In [11]:
df = movies.merge(credit)
df.head()

,title,genres,keywords,overview,movie_id,cast,crew
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
df.isna().sum()

title       0
genres      0
keywords    0
overview    3
movie_id    0
cast        0
crew        0
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.isna().sum()

title       0
genres      0
keywords    0
overview    0
movie_id    0
cast        0
crew        0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
import json

In [17]:
df['genres'] = df['genres'].apply(lambda x: [d['name'] for d in json.loads(x)])

In [18]:
df['keywords'] = df['keywords'].apply(lambda x:[d['name'] for d in json.loads(x)])

In [19]:
# Function to extract first 3 names safely
def extract_cast_names(text):
    parsed = json.loads(text)
    return [item['name'] for item in parsed[:3] if 'name' in item]

In [20]:
df['cast'] = df['cast'].apply(extract_cast_names)

In [21]:
def extract_director(text):
    parsed = json.loads(text)
    job = [item['name'] for item in parsed if item.get('job') == 'Director']
    return job

In [22]:
df['crew'] = df['crew'].apply(extract_director)

In [23]:
df['overview'] = df['overview'].apply(lambda x : x.split())

In [24]:
df.head()

,title,genres,keywords,overview,movie_id,cast,crew
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...",19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...",285,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bond’s, past, send...",206647,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...",49026,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...",49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [25]:
def remove_spaces(obj):
    return [name.replace(' ','') for name in obj]

In [26]:
df['genres'] = df['genres'].apply(remove_spaces)

In [27]:
df['keywords'] = df['keywords'].apply(remove_spaces)

In [28]:
df['cast'] = df['cast'].apply(remove_spaces)

In [29]:
df['crew'] = df['crew'].apply(remove_spaces)

In [30]:
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [31]:
df.head()

,title,genres,keywords,overview,movie_id,cast,crew,tags
0,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",19995,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",285,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",206647,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",49026,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,John Carter,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",49529,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [75]:
newdf = df[['movie_id','title','tags']]

In [76]:
newdf['tags'] = newdf['tags'].apply(lambda x:" ".join(x))

/var/folders/b1/66gwdhd10jd0xh8284xgbmc80000gn/T/ipykernel_27588/1297214613.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x:" ".join(x))

In [93]:
newdf['tags']

0       22nd century paraplegic marine dispatch moon p...
1       captain barbossa long believe dead come back l...
2       cryptic message bond past send trail uncover s...
3       follow death district attorney harvey dent bat...
4       john carter former military captain inexplicab...
                              ...
4804    el mariachi want play guitar carry family trad...
4805    newlywed couple honeymoon upend arrivals respe...
4806    sign seal deliver introduce dedicate quartet c...
4807    ambitious new york attorney sam send shanghai ...
4808    ever since second grade first saw extraterrest...
Name: tags, Length: 4806, dtype: object

In [90]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /Users/mac/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/mac/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/mac/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
def transform_text(text):
    text = text.lower()
    tokens = nltk.word_tokenize(text)

    tokens = [t for t in tokens if t.isalnum()]
    tokens = [t for t in tokens if t not in stopwords.words('english')]

    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(t,pos='v') for t in tokens]
    
    return " ".join(tokens)

In [91]:
newdf['tags'] = newdf['tags'].apply(transform_text)

/var/folders/b1/66gwdhd10jd0xh8284xgbmc80000gn/T/ipykernel_27588/3383486039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(transform_text)

In [92]:
newdf

,movie_id,title,tags
0,19995,Avatar,22nd century paraplegic marine dispatch moon p...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believe dead come back l...
2,206647,Spectre,cryptic message bond past send trail uncover s...
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...
4,49529,John Carter,john carter former military captain inexplicab...
...,...,...,...
4804,9367,El Mariachi,el mariachi want play guitar carry family trad...
4805,72766,Newlyweds,newlywed couple honeymoon upend arrivals respe...
4806,231617,"Signed, Sealed, Delivered",sign seal deliver introduce dedicate quartet c...
4807,126186,Shanghai Calling,ambitious new york attorney sam send shanghai ...
4808,25975,My Date with Drew,ever since second grade first saw extraterrest...

In [94]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=3500)

In [98]:
vectors = tfidf.fit_transform(newdf['tags']).toarray()

In [102]:
len(tfidf.get_feature_names_out())

3500

In [103]:
from sklearn.metrics.pairwise import cosine_similarity

In [124]:
similarity = cosine_similarity(vectors)

In [147]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x: x[1])

[(0, np.float64(1.0000000000000002)),
 (3606, np.float64(0.2000140559654974)),
 (1916, np.float64(0.19191828532133312)),
 (260, np.float64(0.17591709220103707)),
 (47, np.float64(0.17495708141617136)),
 (778, np.float64(0.17471656882551506)),
 (2405, np.float64(0.17227814182037265)),
 (539, np.float64(0.16944755862590366)),
 (3728, np.float64(0.166029120391063)),
 (582, np.float64(0.16432046227847463)),
 (942, np.float64(0.1607221282874468)),
 (3536, np.float64(0.1604920135754742)),
 (1054, np.float64(0.16048165642079854)),
 (1214, np.float64(0.1592453674103656)),
 (507, np.float64(0.15752207821428593)),
 (74, np.float64(0.15677386689432626)),
 (83, np.float64(0.15506914569133368)),
 (1533, np.float64(0.15237354243707812)),
 (1087, np.float64(0.15105701228451612)),
 (1346, np.float64(0.1506938573342167)),
 (2782, np.float64(0.15051862397051266)),
 (61, np.float64(0.14843849457488933)),
 (4046, np.float64(0.1472963765023853)),
 (2969, np.float64(0.14452513557537172)),
 (311, np.float64(0.14360282620213735)),
 (1202, np.float64(0.1432804350855207)),
 (2580, np.float64(0.14322716749925776)),
 (838, np.float64(0.14245979014900145)),
 (4336, np.float64(0.14153623270503915)),
 (4190, np.float64(0.14135557045859945)),
 (300, np.float64(0.1412736927516506)),
 (91, np.float64(0.1398377851901213)),
 (2200, np.float64(0.13853284554926834)),
 (3325, np.float64(0.138186330418648)),
 (1319, np.float64(0.13713069286814633)),
 (1827, np.float64(0.13610908022130952)),
 (1199, np.float64(0.13555945007047313)),
 (3952, np.float64(0.13503452763637605)),
 (322, np.float64(0.1341473537772272)),
 (184, np.float64(0.13319973527755555)),
 (3160, np.float64(0.1322209590817274)),
 (236, np.float64(0.13186525892112194)),
 (27, np.float64(0.12999300834219338)),
 (249, np.float64(0.12937779263161275)),
 (1273, np.float64(0.12857544998115525)),
 (529, np.float64(0.12698052248182837)),
 (1327, np.float64(0.12676908407313794)),
 (373, np.float64(0.12670087071306982)),
 (2329, np.float64(0.12618300921723588)),
 (3671, np.float64(0.1257447597398931)),
 (4228, np.float64(0.12477163456505808)),
 (1069, np.float64(0.12474467197881509)),
 (1440, np.float64(0.12464683312158618)),
 (4, np.float64(0.12438065546207201)),
 (1475, np.float64(0.12437962541344832)),
 (305, np.float64(0.12186550380287639)),
 (1978, np.float64(0.11916996470300718)),
 (2727, np.float64(0.11892042247910325)),
 (2968, np.float64(0.11882538080276242)),
 (466, np.float64(0.11882448095502014)),
 (36, np.float64(0.11783714308832428)),
 (2511, np.float64(0.11774088559400978)),
 (94, np.float64(0.11751967086114784)),
 (2280, np.float64(0.11748082333129675)),
 (495, np.float64(0.1170242560557529)),
 (972, np.float64(0.11700663383400006)),
 (973, np.float64(0.11700663383400006)),
 (301, np.float64(0.11551876421301027)),
 (577, np.float64(0.11516531574620252)),
 (220, np.float64(0.11422652954690263)),
 (502, np.float64(0.1139017786568117)),
 (3997, np.float64(0.11371870899574706)),
 (2869, np.float64(0.11331218576224153)),
 (149, np.float64(0.11174035967020701)),
 (1342, np.float64(0.11148487051399016)),
 (461, np.float64(0.10986050543339901)),
 (4405, np.float64(0.1096188625441089)),
 (740, np.float64(0.10956465540533518)),
 (3980, np.float64(0.10933696263542023)),
 (3974, np.float64(0.1082096994853801)),
 (476, np.float64(0.10817721559508439)),
 (1711, np.float64(0.10744663929908105)),
 (1353, np.float64(0.10742971769775317)),
 (3374, np.float64(0.10689039353289376)),
 (172, np.float64(0.10673087876364479)),
 (2997, np.float64(0.10581987157115286)),
 (1200, np.float64(0.1051266038361637)),
 (1299, np.float64(0.10493246382811434)),
 (1192, np.float64(0.10421810716566292)),
 (843, np.float64(0.10299920656885624)),
 (95, np.float64(0.10279568503608824)),
 (342, np.float64(0.10218504115140199)),
 (579, np.float64(0.10122288372128671)),
 (1961, np.float64(0.1009036485978701)),
 (1271, np.float64(0.09948327991377581)),
 (1176, np.float64(0.09896276847632285)),
 (3299, np.float64(0.09788112536025136)),
 (1374, np.float64(0.09787414048372309)),
 (3626, np.float64(0.09765253564400476)),
 (67, np.float64(0.09749711247791701)),
 (1556, np.float64(0.09747075063050996)),
 (108, np.float64(0.09706410214115928)),
 (3091, np.float64(0.09610939553512099)),
 (3441, np.float64(0.0956799476761506)),
 (168, np.float64(0.09535834342291774)),
 (3407, np.float64(0.09491819846522428)),
 (18, np.float64(0.0947162038198012)),
 (3628, np.float64(0.09452228074600783)),
 (3781, np.float64(0.09439860057280701)),
 (1379, np.float64(0.09395525704129473)),
 (557, np.float64(0.09365659061024156)),
 (513, np.float64(0.09349129390813388)),
 (1164, np.float64(0.09328684055471334)),
 (1320, np.float64(0.09312114200244571)),
 (31, np.float64(0.09271452817777703)),
 (2543, np.float64(0.09234183224517108)),
 (1743, np.float64(0.09182444835625672)),
 (2132, np.float64(0.09180165278751927)),
 (4640, np.float64(0.09144063971591282)),
 (454, np.float64(0.09102634119602991)),
 (1493, np.float64(0.09094736578566187)),
 (41, np.float64(0.0909203839646198)),
 (2165, np.float64(0.09090542860445497)),
 (432, np.float64(0.09017705668092124)),
 (1804, np.float64(0.09014860278936532)),
 (7, np.float64(0.0900588061156763)),
 (1842, np.float64(0.08908242099501543)),
 (3307, np.float64(0.08904952633257143)),
 (1355, np.float64(0.08878175859741477)),
 (275, np.float64(0.08874375144811535)),
 (931, np.float64(0.08869436941961964)),
 (692, np.float64(0.08855705178683942)),
 (158, np.float64(0.08802084296650825)),
 (3233, np.float64(0.08759675315924605)),
 (1941, np.float64(0.08733079510930244)),
 (549, np.float64(0.08693266040837028)),
 (2785, np.float64(0.08667639287710946)),
 (294, np.float64(0.08659282905339198)),
 (1612, np.float64(0.0864470091455236)),
 (2616, np.float64(0.0862544146039263)),
 (777, np.float64(0.08592359629956176)),
 (1761, np.float64(0.08542367235949756)),
 (589, np.float64(0.08539486129376898)),
 (3145, np.float64(0.08539040340379454)),
 (3779, np.float64(0.08522220519201237)),
 (1798, np.float64(0.08449300338669263)),
 (1275, np.float64(0.08401736647426722)),
 (4043, np.float64(0.08372816029417957)),
 (661, np.float64(0.08350403189888014)),
 (1095, np.float64(0.08349233908938501)),
 (2249, np.float64(0.08336954223291558)),
 (52, np.float64(0.0830574505997857)),
 (150, np.float64(0.08229091467570021)),
 (111, np.float64(0.08190077956896102)),
 (1029, np.float64(0.08187656654607094)),
 (368, np.float64(0.0815423721444843)),
 (647, np.float64(0.08134323527174143)),
 (189, np.float64(0.08116827316996549)),
 (581, np.float64(0.08108891215242464)),
 (1000, np.float64(0.08099756310832615)),
 (4793, np.float64(0.07992016255647647)),
 (239, np.float64(0.0797816676993071)),
 (4257, np.float64(0.0794757667225987)),
 (1013, np.float64(0.07929419635338084)),
 (151, np.float64(0.0791638754011194)),
 (2670, np.float64(0.07910266051470642)),
 (26, np.float64(0.078607179340745)),
 (312, np.float64(0.07829641340798253)),
 (2756, np.float64(0.07824344638950587)),
 (46, np.float64(0.07821480815878304)),
 (595, np.float64(0.07808010763049847)),
 (1508, np.float64(0.07783132472474143)),
 (2640, np.float64(0.0777925355732912)),
 (4077, np.float64(0.07761580779429085)),
 (3081, np.float64(0.07689706179544176)),
 (422, np.float64(0.0766958497946077)),
 (1369, np.float64(0.07622295762038905)),
 (2446, np.float64(0.07616942556314517)),
 (568, np.float64(0.07596835212765418)),
 (2246, np.float64(0.07585988288123331)),
 (332, np.float64(0.07582653614213793)),
 (1484, np.float64(0.07556726403818494)),
 (1934, np.float64(0.07549060436480726)),
 (3460, np.float64(0.07530886606130202)),
 (889, np.float64(0.07530557310344489)),
 (635, np.float64(0.07521655601060663)),
 (1570, np.float64(0.07466397220818606)),
 (487, np.float64(0.07445430938090444)),
 (2492, np.float64(0.0743109856731614)),
 (900, np.float64(0.0743045952181963)),
 (45, np.float64(0.07415773840842618)),
 (1737, np.float64(0.07408719535787295)),
 (17, np.float64(0.07390948749133452)),
 (1819, np.float64(0.07386476919533039)),
 (908, np.float64(0.07332870816272836)),
 (1005, np.float64(0.07315027987134967)),
 (2129, np.float64(0.07304113047591253)),
 (847, np.float64(0.07269215152846875)),
 (1392, np.float64(0.07233788932815903)),
 (141, np.float64(0.07232571571177211)),
 (3659, np.float64(0.0720989578070276)),
 (2108, np.float64(0.07203364120052919)),
 (1469, np.float64(0.07197136948023629)),
 (1786, np.float64(0.07191445425304252)),
 (4016, np.float64(0.07185107553288592)),
 (668, np.float64(0.07161364842377169)),
 (4468, np.float64(0.07160262023109627)),
 (281, np.float64(0.07151762743263129)),
 (752, np.float64(0.07115483269911728)),
 (2105, np.float64(0.07103118005942008)),
 (3107, np.float64(0.07100445246623802)),
 (2630, np.float64(0.0709163019970799)),
 (2228, np.float64(0.07073584887298119)),
 (643, np.float64(0.07026908408941612)),
 (483, np.float64(0.07024474500450102)),
 (937, np.float64(0.07018541639761587)),
 (754, np.float64(0.07011968575823913)),
 (174, np.float64(0.070024675394826)),
 (449, np.float64(0.06994400880766903)),
 (206, np.float64(0.06993319294673686)),
 (3718, np.float64(0.06991014554252287)),
 (127, np.float64(0.06952148768814298)),
 (2095, np.float64(0.06940001167493264)),
 (2648, np.float64(0.06938137811991517)),
 (2736, np.float64(0.06936137001411574)),
 (4545, np.float64(0.06916824791850476)),
 (2502, np.float64(0.06873015671743947)),
 (2709, np.float64(0.06825985519187376)),
 (2177, np.float64(0.06787693278313793)),
 (646, np.float64(0.06765943484032202)),
 (68, np.float64(0.06743490785189421)),
 (1143, np.float64(0.06732872182907233)),
 (87, np.float64(0.06720236599995826)),
 (1874, np.float64(0.06708450330144236)),
 (3352, np.float64(0.0668816329021964)),
 (2836, np.float64(0.06670411653272794)),
 (2368, np.float64(0.06656660150690348)),
 (541, np.float64(0.06629506356343239)),
 (3872, np.float64(0.06621956875937579)),
 (1080, np.float64(0.06619638238317657)),
 (85, np.float64(0.0659923976886904)),
 (3620, np.float64(0.06586955480967138)),
 (4506, np.float64(0.0658547129156144)),
 (2014, np.float64(0.06557035379138892)),
 (1414, np.float64(0.06554465658914117)),
 (1435, np.float64(0.06543126720382524)),
 (1696, np.float64(0.06540748714083597)),
 (160, np.float64(0.06538049903808775)),
 (2484, np.float64(0.06537798505491602)),
 (4095, np.float64(0.06536862801771355)),
 (3699, np.float64(0.06535338979282992)),
 (3551, np.float64(0.065246276138919)),
 (182, np.float64(0.064815635642513)),
 (4196, np.float64(0.06468382770718543)),
 (3100, np.float64(0.06466694974254523)),
 (1218, np.float64(0.06445494863650668)),
 (307, np.float64(0.06443265066359141)),
 (302, np.float64(0.06437246000932705)),
 (3006, np.float64(0.06431769785827253)),
 (244, np.float64(0.0641972417597384)),
 (2656, np.float64(0.06408471954347193)),
 (134, np.float64(0.06389509660058412)),
 (570, np.float64(0.0637532826830162)),
 (479, np.float64(0.06360748350796859)),
 (2523, np.float64(0.06345813919230184)),
 (624, np.float64(0.06324183999807931)),
 (3210, np.float64(0.0629524458915395)),
 (2936, np.float64(0.06290737143384934)),
 (1154, np.float64(0.06289917431933122)),
 (166, np.float64(0.06272991220640804)),
 (139, np.float64(0.06260345328112157)),
 (2243, np.float64(0.06251576614831235)),
 (266, np.float64(0.06250014479356013)),
 (1894, np.float64(0.06240175736361315)),
 (2783, np.float64(0.062273872765879756)),
 (3446, np.float64(0.06202500985409935)),
 (505, np.float64(0.06194116416582731)),
 (1677, np.float64(0.06186381747959435)),
 (313, np.float64(0.06180698845656162)),
 (564, np.float64(0.061762153166630834)),
 (126, np.float64(0.06158950116704248)),
 (102, np.float64(0.06154368897415868)),
 (3908, np.float64(0.06154222345807082)),
 (1295, np.float64(0.06136303167029593)),
 (1272, np.float64(0.06133897679792061)),
 (3439, np.float64(0.06118027404195584)),
 (2089, np.float64(0.061081059460630666)),
 (1302, np.float64(0.06106812323804916)),
 (1401, np.float64(0.06091960920717257)),
 (5, np.float64(0.06089006489675222)),
 (2790, np.float64(0.06086790959810586)),
 (56, np.float64(0.0608582658429016)),
 (1451, np.float64(0.060829931886311424)),
 (3462, np.float64(0.0604496046332816)),
 (3297, np.float64(0.06040620423536022)),
 (614, np.float64(0.06029639268340106)),
 (2155, np.float64(0.06005604916137493)),
 (208, np.float64(0.059859036200084786)),
 (4118, np.float64(0.05979078223608806)),
 (2144, np.float64(0.059751485142630525)),
 (2237, np.float64(0.059677175346458736)),
 (75, np.float64(0.05964829527080498)),
 (1552, np.float64(0.059626452443555446)),
 (170, np.float64(0.05959083573626131)),
 (2374, np.float64(0.059349231198696506)),
 (1276, np.float64(0.059321704843979875)),
 (3476, np.float64(0.05916117817034469)),
 (59, np.float64(0.059050071989889694)),
 (107, np.float64(0.05894837706546295)),
 (3429, np.float64(0.05894427959646946)),
 (473, np.float64(0.05887548701770042)),
 (775, np.float64(0.05871525078936696)),
 (1663, np.float64(0.05871006071958966)),
 (812, np.float64(0.058698324567548976)),
 (4559, np.float64(0.05863279191423582)),
 (228, np.float64(0.058322680348205785)),
 (2813, np.float64(0.05819629764229216)),
 (4305, np.float64(0.05805261283702931)),
 (1770, np.float64(0.05790129832573722)),
 (3018, np.float64(0.05778453203400596)),
 (808, np.float64(0.05761529383868305)),
 (4408, np.float64(0.05745756792299967)),
 (1043, np.float64(0.05742449562722885)),
 (1610, np.float64(0.057303607447585586)),
 (2406, np.float64(0.057282060369670734)),
 (3734, np.float64(0.05727646822150557)),
 (939, np.float64(0.05725922862999382)),
 (1014, np.float64(0.05708090467709061)),
 (1902, np.float64(0.05702757413692805)),
 (1035, np.float64(0.05689785249879897)),
 (2714, np.float64(0.05689321740926353)),
 (791, np.float64(0.0568582168519629)),
 (262, np.float64(0.056679574882363644)),
 (898, np.float64(0.0565404297823169)),
 (2768, np.float64(0.05635400689526658)),
 (3595, np.float64(0.056309771465979486)),
 (951, np.float64(0.05618846922151261)),
 (480, np.float64(0.05600940357998439)),
 (687, np.float64(0.0559795630596712)),
 (1482, np.float64(0.05597659464842797)),
 (4654, np.float64(0.05572162182871221)),
 (1017, np.float64(0.05566422324781181)),
 (123, np.float64(0.055645167428060256)),
 (1613, np.float64(0.05563449247193399)),
 (3115, np.float64(0.05555697228345863)),
 (3928, np.float64(0.055438238368276826)),
 (2644, np.float64(0.05525149343798799)),
 (1107, np.float64(0.055222779082182136)),
 (1094, np.float64(0.0552143585736691)),
 (1527, np.float64(0.05518873972392251)),
 (3387, np.float64(0.055007028186682315)),
 (1147, np.float64(0.05484984226203092)),
 (626, np.float64(0.054783214523079896)),
 (1828, np.float64(0.05462607965683959)),
 (254, np.float64(0.05459884321376002)),
 (2618, np.float64(0.054594369364386025)),
 (2571, np.float64(0.05459406043609089)),
 (1925, np.float64(0.05452115642049646)),
 (3058, np.float64(0.05450046861259712)),
 (3026, np.float64(0.05439364318175596)),
 (1824, np.float64(0.05431333825988388)),
 (1045, np.float64(0.054312463319647536)),
 (491, np.float64(0.05428145699419271)),
 (278, np.float64(0.054279783325372685)),
 (2788, np.float64(0.054262387279151385)),
 (854, np.float64(0.054204828880689615)),
 (4587, np.float64(0.05420302326370108)),
 (2864, np.float64(0.05414276133638116)),
 (2708, np.float64(0.054120982696900556)),
 (3540, np.float64(0.05397342663885431)),
 (238, np.float64(0.053969388363362666)),
 (3933, np.float64(0.053849039918947614)),
 (701, np.float64(0.053786404904595964)),
 (4412, np.float64(0.053540784384177344)),
 (222, np.float64(0.053483576451610455)),
 (4591, np.float64(0.05343899935472736)),
 (1442, np.float64(0.053429240442994394)),
 (28, np.float64(0.05308737330697246)),
 (105, np.float64(0.05306305284813112)),
 (1404, np.float64(0.05286641147273943)),
 (1246, np.float64(0.05284689610927711)),
 (1651, np.float64(0.05284535751304334)),
 (1608, np.float64(0.0528331516875814)),
 (363, np.float64(0.0528285773102056)),
 (3193, np.float64(0.0527280673394908)),
 (246, np.float64(0.05271081257216732)),
 (674, np.float64(0.05263159394558446)),
 (1292, np.float64(0.052615329390019186)),
 (1156, np.float64(0.05248034927586987)),
 (2525, np.float64(0.05241732538357985)),
 (270, np.float64(0.05230115378231616)),
 (510, np.float64(0.05224116525053523)),
 (3338, np.float64(0.05219366016493664)),
 (420, np.float64(0.05214363649319525)),
 (3447, np.float64(0.05213558498459023)),
 (362, np.float64(0.05212808801027004)),
 (4624, np.float64(0.05201239680358995)),
 (2779, np.float64(0.05195385666817292)),
 (2697, np.float64(0.0519427928327438)),
 (2255, np.float64(0.05181210522320821)),
 (3342, np.float64(0.05164290770676198)),
 (223, np.float64(0.05162402817996749)),
 (4744, np.float64(0.0515405308267375)),
 (4673, np.float64(0.051465095171820296)),
 (157, np.float64(0.05145796749305669)),
 (2759, np.float64(0.05145483349550413)),
 (4652, np.float64(0.0513871586528485)),
 (1635, np.float64(0.05133829262897818)),
 (3797, np.float64(0.05132077170127569)),
 (773, np.float64(0.051284289427815974)),
 (187, np.float64(0.05126853641535565)),
 (787, np.float64(0.051264121584507535)),
 (1519, np.float64(0.051253310458767035)),
 (81, np.float64(0.05116230636156775)),
 (3879, np.float64(0.05113466782356184)),
 (3558, np.float64(0.05103717827632476)),
 (4004, np.float64(0.05102368972662683)),
 (3421, np.float64(0.05101300386867256)),
 (4626, np.float64(0.050943211302534715)),
 (3398, np.float64(0.05090658037735879)),
 (2435, np.float64(0.050824437916238516)),
 (14, np.float64(0.050817255702933356)),
 (2062, np.float64(0.05076058522917247)),
 (2372, np.float64(0.05065679228361153)),
 (2384, np.float64(0.050597493298832744)),
 (4241, np.float64(0.05055721066284981)),
 (1034, np.float64(0.05054100891307604)),
 (492, np.float64(0.05038284458014014)),
 (4451, np.float64(0.05031207985887239)),
 (995, np.float64(0.05010233858206936)),
 (3216, np.float64(0.050081206036475395)),
 (4718, np.float64(0.04997993609839671)),
 (2628, np.float64(0.049957519668378254)),
 (1530, np.float64(0.04975764793602075)),
 (870, np.float64(0.04971704635148611)),
 (3753, np.float64(0.049653561564130345)),
 (2363, np.float64(0.04964835830165142)),
 (279, np.float64(0.04964540516863822)),
 (1310, np.float64(0.049629499883952516)),
 (4538, np.float64(0.049504108536511465)),
 (2737, np.float64(0.049490368472494634)),
 (415, np.float64(0.04930315179812956)),
 (365, np.float64(0.04929912031280583)),
 (704, np.float64(0.04929652799454358)),
 (179, np.float64(0.049248725076531275)),
 (2655, np.float64(0.04916390258786928)),
 (3899, np.float64(0.04900125350976359)),
 (4179, np.float64(0.0489467743411249)),
 (2452, np.float64(0.0486650859376537)),
 (4343, np.float64(0.04866468355807838)),
 (1084, np.float64(0.04856570748971826)),
 (1483, np.float64(0.04856218100213157)),
 (230, np.float64(0.048522444386340395)),
 (274, np.float64(0.048331502173881616)),
 (97, np.float64(0.048326365635021996)),
 (1159, np.float64(0.048310426083616576)),
 (84, np.float64(0.04818277216586618)),
 (304, np.float64(0.04815137120883118)),
 (3204, np.float64(0.048061055806994865)),
 (43, np.float64(0.04798832257389432)),
 (467, np.float64(0.04783022717353682)),
 (1571, np.float64(0.04782961020147)),
 (535, np.float64(0.04782406776757642)),
 (193, np.float64(0.04781557440782676)),
 (632, np.float64(0.04779154186072002)),
 (600, np.float64(0.047774607505245884)),
 (935, np.float64(0.047731636910570155)),
 (781, np.float64(0.047711458000839785)),
 (4799, np.float64(0.04771032377897458)),
 (1953, np.float64(0.04768515261788895)),
 (2807, np.float64(0.04768028810531169)),
 (3738, np.float64(0.04766439642655903)),
 (4623, np.float64(0.0476148587377547)),
 (86, np.float64(0.047591773508679575)),
 (1549, np.float64(0.04757028251270488)),
 (1436, np.float64(0.04756907262555965)),
 (2548, np.float64(0.04748959469967356)),
 (21, np.float64(0.04742572337757933)),
 (404, np.float64(0.047338301377891655)),
 (1765, np.float64(0.04727946639122083)),
 (2646, np.float64(0.047199742774281676)),

In [157]:
def recommend(movie):
    movie_index = newdf[newdf['title'] == movie].index[0]
    top_movies = sorted(list(enumerate(similarity[movie_index])),reverse=True,key=lambda x: x[1])[1:6]
    for i in top_movies:
        print(newdf.iloc[i[0]].title)

In [163]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman v Superman: Dawn of Justice
Batman Returns
Batman

In [164]:
newdf

,movie_id,title,tags
0,19995,Avatar,22nd century paraplegic marine dispatch moon p...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believe dead come back l...
2,206647,Spectre,cryptic message bond past send trail uncover s...
3,49026,The Dark Knight Rises,follow death district attorney harvey dent bat...
4,49529,John Carter,john carter former military captain inexplicab...
...,...,...,...
4804,9367,El Mariachi,el mariachi want play guitar carry family trad...
4805,72766,Newlyweds,newlywed couple honeymoon upend arrivals respe...
4806,231617,"Signed, Sealed, Delivered",sign seal deliver introduce dedicate quartet c...
4807,126186,Shanghai Calling,ambitious new york attorney sam send shanghai ...
4808,25975,My Date with Drew,ever since second grade first saw extraterrest...

In [165]:
import pickle

In [166]:
pickle.dump(newdf,open('newdf.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))